version: '2'

# Bring up a dev environment

services:
    web:
        image: nginx:alpine
        ports:
            - "8045:80"
        volumes:
            - .:/code
            - /Volumes/Datentonne/Rollenspiel:/pdf:ro
            - ./.docker/site.conf:/etc/nginx/conf.d/default.conf
    php:
        build: .docker
        volumes:
            - .:/code
            - /Volumes/Datentonne/Rollenspiel:/pdf:ro
            - ./.docker/log.conf:/usr/local/etc/php-fpm.d/zz-log.conf

