version: '2'

# Bring up a dev environment
# The volumes for /pdf and /site are highly specific to my machine

services:
    web:
        image: nginx:alpine
        ports:
            - "8045:8045"
        volumes:
            - ./.docker/site.template:/etc/nginx/conf.d/site.template
            - .:/thumbnail-srv
            - /Volumes/Datentonne/Rollenspiel:/pdf:ro
            - /Users/gbirke/src/astro-rpg-list/dist:/site:ro
            - thumbnails:/thumbnails:ro
        environment:
          - NGINX_PORT="8045"
        command: /bin/sh -c "envsubst '$$NGINX_PORT' < /etc/nginx/conf.d/site.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"
    php:
        build: .docker
        volumes:
            - .:/thumbnail-srv
            - thumbnails:/thumbnails
            - /Volumes/Datentonne/Rollenspiel:/pdf:ro

volumes:
  thumbnails:
